// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	CommonAck
	BlankMsg
	LoginReq
	LoginAck
	LogoutReq
	LogoutAck
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonAck struct {
	Status    int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	TimeStamp uint32 `protobuf:"varint,2,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CommonAck) Reset()                    { *m = CommonAck{} }
func (m *CommonAck) String() string            { return proto.CompactTextString(m) }
func (*CommonAck) ProtoMessage()               {}
func (*CommonAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommonAck) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CommonAck) GetTimeStamp() uint32 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *CommonAck) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BlankMsg struct {
	Helper bool `protobuf:"varint,1,opt,name=helper" json:"helper,omitempty"`
}

func (m *BlankMsg) Reset()                    { *m = BlankMsg{} }
func (m *BlankMsg) String() string            { return proto.CompactTextString(m) }
func (*BlankMsg) ProtoMessage()               {}
func (*BlankMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BlankMsg) GetHelper() bool {
	if m != nil {
		return m.Helper
	}
	return false
}

type LoginReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Uuid   string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type LoginAck struct {
	Common *CommonAck `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
}

func (m *LoginAck) Reset()                    { *m = LoginAck{} }
func (m *LoginAck) String() string            { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()               {}
func (*LoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginAck) GetCommon() *CommonAck {
	if m != nil {
		return m.Common
	}
	return nil
}

type LogoutReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LogoutReq) Reset()                    { *m = LogoutReq{} }
func (m *LogoutReq) String() string            { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()               {}
func (*LogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogoutReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LogoutAck struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *LogoutAck) Reset()                    { *m = LogoutAck{} }
func (m *LogoutAck) String() string            { return proto.CompactTextString(m) }
func (*LogoutAck) ProtoMessage()               {}
func (*LogoutAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LogoutAck) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonAck)(nil), "CommonAck")
	proto.RegisterType((*BlankMsg)(nil), "BlankMsg")
	proto.RegisterType((*LoginReq)(nil), "LoginReq")
	proto.RegisterType((*LoginAck)(nil), "LoginAck")
	proto.RegisterType((*LogoutReq)(nil), "LogoutReq")
	proto.RegisterType((*LogoutAck)(nil), "LogoutAck")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0xc5, 0x20,
	0x14, 0x85, 0xf3, 0x9e, 0x4a, 0xcb, 0x6d, 0x5c, 0x18, 0x94, 0xc1, 0xc1, 0x10, 0x07, 0xa7, 0x0e,
	0x3a, 0x38, 0xab, 0x93, 0x89, 0x2e, 0x38, 0x3a, 0x18, 0x6c, 0x6f, 0x6a, 0xd3, 0x52, 0xb0, 0xc0,
	0xe0, 0xbf, 0x17, 0x08, 0xda, 0xc9, 0xb7, 0x71, 0xce, 0xf9, 0xee, 0x81, 0x0b, 0x34, 0xfe, 0xdb,
	0xa2, 0x6b, 0xed, 0x6a, 0xbc, 0x11, 0x6f, 0x40, 0x1f, 0x8d, 0xd6, 0x66, 0xb9, 0xef, 0x26, 0x76,
	0x06, 0xc4, 0x79, 0xe5, 0x83, 0xe3, 0xbb, 0xcb, 0xdd, 0xf5, 0x89, 0x2c, 0x8a, 0x5d, 0x00, 0xf5,
	0xa3, 0xc6, 0x57, 0xaf, 0xb4, 0xe5, 0xfb, 0x18, 0x9d, 0xca, 0xcd, 0x60, 0x1c, 0x2a, 0x8d, 0xce,
	0xa9, 0x01, 0xf9, 0x51, 0xcc, 0xa8, 0xfc, 0x95, 0x42, 0x40, 0xfd, 0x30, 0xab, 0x65, 0x7a, 0x71,
	0x43, 0xea, 0xfe, 0xc4, 0xd9, 0xe2, 0x9a, 0xbb, 0x6b, 0x59, 0x94, 0xb8, 0x83, 0xfa, 0xd9, 0x0c,
	0xe3, 0x22, 0xf1, 0x8b, 0x9d, 0x43, 0x15, 0x1c, 0xae, 0xef, 0x63, 0x9f, 0x21, 0x2a, 0x49, 0x92,
	0x4f, 0x3d, 0x63, 0x70, 0x1c, 0x42, 0x74, 0xf7, 0xd9, 0xcd, 0x67, 0xd1, 0x96, 0xc1, 0xf4, 0x70,
	0x01, 0xa4, 0xcb, 0x5b, 0xe4, 0xb9, 0xe6, 0x06, 0xda, 0xbf, 0xa5, 0x64, 0x49, 0xc4, 0x15, 0xd0,
	0xc8, 0x9b, 0xe0, 0x0f, 0xdd, 0xb4, 0x51, 0xa9, 0xf6, 0x3f, 0xea, 0x83, 0xe4, 0xcf, 0xbb, 0xfd,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xf8, 0xce, 0x10, 0x4b, 0x01, 0x00, 0x00,
}
