// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	ServerLoginReq
	ServerLoginAck
	ServerLoginOut
	AddBrdCastMemberReq
	AddBrdCastMemberAck
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerLoginReq struct {
	ServerId   string `protobuf:"bytes,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerName string `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
}

func (m *ServerLoginReq) Reset()                    { *m = ServerLoginReq{} }
func (m *ServerLoginReq) String() string            { return proto.CompactTextString(m) }
func (*ServerLoginReq) ProtoMessage()               {}
func (*ServerLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerLoginReq) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ServerLoginReq) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

type ServerLoginAck struct {
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
}

func (m *ServerLoginAck) Reset()                    { *m = ServerLoginAck{} }
func (m *ServerLoginAck) String() string            { return proto.CompactTextString(m) }
func (*ServerLoginAck) ProtoMessage()               {}
func (*ServerLoginAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerLoginAck) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

type ServerLoginOut struct {
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	Status   int32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *ServerLoginOut) Reset()                    { *m = ServerLoginOut{} }
func (m *ServerLoginOut) String() string            { return proto.CompactTextString(m) }
func (*ServerLoginOut) ProtoMessage()               {}
func (*ServerLoginOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServerLoginOut) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ServerLoginOut) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AddBrdCastMemberReq struct {
	GroupId   string   `protobuf:"bytes,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberIds []string `protobuf:"bytes,2,rep,name=member_ids,json=memberIds" json:"member_ids,omitempty"`
}

func (m *AddBrdCastMemberReq) Reset()                    { *m = AddBrdCastMemberReq{} }
func (m *AddBrdCastMemberReq) String() string            { return proto.CompactTextString(m) }
func (*AddBrdCastMemberReq) ProtoMessage()               {}
func (*AddBrdCastMemberReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddBrdCastMemberReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *AddBrdCastMemberReq) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

type AddBrdCastMemberAck struct {
	GroupId   string `protobuf:"bytes,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberNum int32  `protobuf:"varint,2,opt,name=member_num,json=memberNum" json:"member_num,omitempty"`
}

func (m *AddBrdCastMemberAck) Reset()                    { *m = AddBrdCastMemberAck{} }
func (m *AddBrdCastMemberAck) String() string            { return proto.CompactTextString(m) }
func (*AddBrdCastMemberAck) ProtoMessage()               {}
func (*AddBrdCastMemberAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddBrdCastMemberAck) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *AddBrdCastMemberAck) GetMemberNum() int32 {
	if m != nil {
		return m.MemberNum
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerLoginReq)(nil), "ServerLoginReq")
	proto.RegisterType((*ServerLoginAck)(nil), "ServerLoginAck")
	proto.RegisterType((*ServerLoginOut)(nil), "ServerLoginOut")
	proto.RegisterType((*AddBrdCastMemberReq)(nil), "AddBrdCastMemberReq")
	proto.RegisterType((*AddBrdCastMemberAck)(nil), "AddBrdCastMemberAck")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe3, 0xe2, 0x0b, 0x4e, 0x2d, 0x2a, 0x4b,
	0x2d, 0xf2, 0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x4a, 0x2d, 0x14, 0x92, 0xe6, 0xe2, 0x2c, 0x06, 0x8b,
	0xc4, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x40, 0x04, 0x3c, 0x53, 0x84,
	0xe4, 0xb9, 0xb8, 0xa1, 0x92, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x69, 0x2e, 0x88, 0x90,
	0x1f, 0x50, 0x44, 0x49, 0x17, 0xc5, 0x3c, 0xc7, 0xe4, 0x6c, 0xbc, 0xe6, 0x29, 0xb9, 0xa2, 0x28,
	0xf7, 0x2f, 0x2d, 0xc1, 0x6f, 0xbd, 0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0x31, 0xd8,
	0x66, 0xd6, 0x20, 0x28, 0x4f, 0xc9, 0x9f, 0x4b, 0xd8, 0x31, 0x25, 0xc5, 0xa9, 0x28, 0xc5, 0x39,
	0xb1, 0xb8, 0xc4, 0x37, 0x35, 0x37, 0x29, 0xb5, 0x08, 0xe4, 0x15, 0x49, 0x2e, 0x8e, 0xf4, 0xa2,
	0xfc, 0xd2, 0x02, 0x84, 0x51, 0xec, 0x60, 0x3e, 0xd0, 0x24, 0x59, 0x2e, 0xae, 0x5c, 0xb0, 0x3a,
	0xa0, 0x1c, 0xc8, 0x34, 0x66, 0xa0, 0x24, 0x27, 0x44, 0xc4, 0x33, 0x05, 0xab, 0x81, 0x20, 0xbf,
	0x10, 0x65, 0x60, 0x5e, 0x69, 0x2e, 0xd4, 0x79, 0x50, 0x03, 0xfd, 0x4a, 0x73, 0x93, 0xd8, 0xc0,
	0xc1, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xe6, 0x1f, 0x72, 0x7d, 0x01, 0x00, 0x00,
}
